services:
  blueprint-ai-bom-backend:
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: 1
            driver: nvidia
  edgnet-api:
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: 1
            driver: nvidia
  edocr2-v2-api:
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: 1
            driver: nvidia
  esrgan-api:
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: 1
            driver: nvidia
  line-detector-api:
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: 1
            driver: nvidia
  paddleocr-api:
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: 1
            driver: nvidia
  trocr-api:
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: 1
            driver: nvidia
  table-detector-api:
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            count: 1
            driver: nvidia
  yolo-api:
    deploy:
      resources:
        reservations:
          devices: []
